# Generated by Django 5.2 on 2025-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatarUrl',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
