# Generated by Django 5.2 on 2025-05-31 11:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatarurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatarUrl',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='avatars/'),
        ),
    ]
